//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.01.10 at 08:57:27 PM CET 
//


package main.java.com.xml.officialbackend.model.izvestaj_o_imunizaciji;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the rs.ac.uns.ftn.izvestaj_o_imunizaciji package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: rs.ac.uns.ftn.izvestaj_o_imunizaciji
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link IzvestajOImunizaciji }
     * 
     */
    public IzvestajOImunizaciji createIzvestajOImunizaciji() {
        return new IzvestajOImunizaciji();
    }

    /**
     * Create an instance of {@link IzvestajOImunizaciji.RaspodelaProizvodjaca }
     * 
     */
    public IzvestajOImunizaciji.RaspodelaProizvodjaca createIzvestajOImunizacijiRaspodelaProizvodjaca() {
        return new IzvestajOImunizaciji.RaspodelaProizvodjaca();
    }

    /**
     * Create an instance of {@link IzvestajOImunizaciji.Period }
     * 
     */
    public IzvestajOImunizaciji.Period createIzvestajOImunizacijiPeriod() {
        return new IzvestajOImunizaciji.Period();
    }

    /**
     * Create an instance of {@link IzvestajOImunizaciji.DatumIzdavanja }
     * 
     */
    public IzvestajOImunizaciji.DatumIzdavanja createIzvestajOImunizacijiDatumIzdavanja() {
        return new IzvestajOImunizaciji.DatumIzdavanja();
    }

    /**
     * Create an instance of {@link IzvestajOImunizaciji.RaspodelaProizvodjaca.Vakcina }
     * 
     */
    public IzvestajOImunizaciji.RaspodelaProizvodjaca.Vakcina createIzvestajOImunizacijiRaspodelaProizvodjacaVakcina() {
        return new IzvestajOImunizaciji.RaspodelaProizvodjaca.Vakcina();
    }

    /**
     * Create an instance of {@link IzvestajOImunizaciji.Period.Od }
     * 
     */
    public IzvestajOImunizaciji.Period.Od createIzvestajOImunizacijiPeriodOd() {
        return new IzvestajOImunizaciji.Period.Od();
    }

    /**
     * Create an instance of {@link IzvestajOImunizaciji.Period.Do }
     * 
     */
    public IzvestajOImunizaciji.Period.Do createIzvestajOImunizacijiPeriodDo() {
        return new IzvestajOImunizaciji.Period.Do();
    }

}
