//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.02.16 at 11:43:20 PM CET 
//


package main.java.com.xml.officialbackend.model.zahtev_za_sertifikat;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the rs.ac.uns.ftn.zahtev_za_sertifikat package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: rs.ac.uns.ftn.zahtev_za_sertifikat
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ZahtevZaIzdavanjeSertifikata }
     * 
     */
    public ZahtevZaIzdavanjeSertifikata createZahtevZaIzdavanjeSertifikata() {
        return new ZahtevZaIzdavanjeSertifikata();
    }

    /**
     * Create an instance of {@link Osoba }
     * 
     */
    public Osoba createOsoba() {
        return new Osoba();
    }

    /**
     * Create an instance of {@link ZahtevZaIzdavanjeSertifikata.DatumPodnosenjaZahteva }
     * 
     */
    public ZahtevZaIzdavanjeSertifikata.DatumPodnosenjaZahteva createZahtevZaIzdavanjeSertifikataDatumPodnosenjaZahteva() {
        return new ZahtevZaIzdavanjeSertifikata.DatumPodnosenjaZahteva();
    }

    /**
     * Create an instance of {@link Jmbg }
     * 
     */
    public Jmbg createJmbg() {
        return new Jmbg();
    }

    /**
     * Create an instance of {@link BrojPasosa }
     * 
     */
    public BrojPasosa createBrojPasosa() {
        return new BrojPasosa();
    }

}
