//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.02.10 at 06:03:11 PM CET 
//


package main.java.com.xml.officialbackend.model.obrazac_za_sprovodjenje_imunizacije;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the rs.ac.uns.ftn.obrazac_za_sprovodjenje_imunizacije package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: rs.ac.uns.ftn.obrazac_za_sprovodjenje_imunizacije
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ObrazacZaSprovodjenjeImunizacije }
     * 
     */
    public ObrazacZaSprovodjenjeImunizacije createObrazacZaSprovodjenjeImunizacije() {
        return new ObrazacZaSprovodjenjeImunizacije();
    }

    /**
     * Create an instance of {@link Doza }
     * 
     */
    public Doza createDoza() {
        return new Doza();
    }

    /**
     * Create an instance of {@link Osoba }
     *
     */
    public Osoba createOsoba() {
        return new Osoba();
    }

    /**
     * Create an instance of {@link ObrazacZaSprovodjenjeImunizacije.PodaciKojeJePopunioZdravstveniRadnik }
     *
     */
    public ObrazacZaSprovodjenjeImunizacije.PodaciKojeJePopunioZdravstveniRadnik createObrazacZaSprovodjenjeImunizacijePodaciKojeJePopunioZdravstveniRadnik() {
        return new ObrazacZaSprovodjenjeImunizacije.PodaciKojeJePopunioZdravstveniRadnik();
    }

    /**
     * Create an instance of {@link ObrazacZaSprovodjenjeImunizacije.PodaciKojeJePopunioPacijent }
     *
     */
    public ObrazacZaSprovodjenjeImunizacije.PodaciKojeJePopunioPacijent createObrazacZaSprovodjenjeImunizacijePodaciKojeJePopunioPacijent() {
        return new ObrazacZaSprovodjenjeImunizacije.PodaciKojeJePopunioPacijent();
    }

    /**
     * Create an instance of {@link PodaciOAdresi }
     *
     */
    public PodaciOAdresi createPodaciOAdresi() {
        return new PodaciOAdresi();
    }

    /**
     * Create an instance of {@link Jmbg }
     *
     */
    public Jmbg createJmbg() {
        return new Jmbg();
    }

    /**
     * Create an instance of {@link Doza.DatumDavanjaVakcine }
     *
     */
    public Doza.DatumDavanjaVakcine createDozaDatumDavanjaVakcine() {
        return new Doza.DatumDavanjaVakcine();
    }

    /**
     * Create an instance of {@link Osoba.BrojPasosa }
     *
     */
    public Osoba.BrojPasosa createOsobaBrojPasosa() {
        return new Osoba.BrojPasosa();
    }

    /**
     * Create an instance of {@link ObrazacZaSprovodjenjeImunizacije.PodaciKojeJePopunioZdravstveniRadnik.Doze }
     * 
     */
    public ObrazacZaSprovodjenjeImunizacije.PodaciKojeJePopunioZdravstveniRadnik.Doze createObrazacZaSprovodjenjeImunizacijePodaciKojeJePopunioZdravstveniRadnikDoze() {
        return new ObrazacZaSprovodjenjeImunizacije.PodaciKojeJePopunioZdravstveniRadnik.Doze();
    }

    /**
     * Create an instance of {@link ObrazacZaSprovodjenjeImunizacije.PodaciKojeJePopunioPacijent.ZeljenaVakcina }
     * 
     */
    public ObrazacZaSprovodjenjeImunizacije.PodaciKojeJePopunioPacijent.ZeljenaVakcina createObrazacZaSprovodjenjeImunizacijePodaciKojeJePopunioPacijentZeljenaVakcina() {
        return new ObrazacZaSprovodjenjeImunizacije.PodaciKojeJePopunioPacijent.ZeljenaVakcina();
    }

    /**
     * Create an instance of {@link ObrazacZaSprovodjenjeImunizacije.PodaciKojeJePopunioPacijent.Datum }
     * 
     */
    public ObrazacZaSprovodjenjeImunizacije.PodaciKojeJePopunioPacijent.Datum createObrazacZaSprovodjenjeImunizacijePodaciKojeJePopunioPacijentDatum() {
        return new ObrazacZaSprovodjenjeImunizacije.PodaciKojeJePopunioPacijent.Datum();
    }

}
