//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.02.16 at 05:55:23 PM CET 
//


package main.java.com.xml.officialbackend.model.obrazac_za_sprovodjenje_imunizacije;

import javax.xml.bind.annotation.*;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for osoba complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="osoba"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;choice&gt;
 *           &lt;sequence&gt;
 *             &lt;element name="drzavljanstvo" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *             &lt;element name="jmbg" type="{http://www.ftn.uns.ac.rs/obrazac_za_sprovodjenje_imunizacije}jmbg"/&gt;
 *           &lt;/sequence&gt;
 *           &lt;sequence&gt;
 *             &lt;element name="strano_drzavljanstvo" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *             &lt;element name="broj_pasosa"&gt;
 *               &lt;complexType&gt;
 *                 &lt;simpleContent&gt;
 *                   &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
 *                   &lt;/extension&gt;
 *                 &lt;/simpleContent&gt;
 *               &lt;/complexType&gt;
 *             &lt;/element&gt;
 *           &lt;/sequence&gt;
 *         &lt;/choice&gt;
 *         &lt;element name="prezime" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="ime" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="ime_roditelja" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="pol"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;enumeration value="Z"/&gt;
 *               &lt;enumeration value="M"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="datum_rodjenja" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
 *         &lt;element name="mesto_rodjenja" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="adresa" type="{http://www.ftn.uns.ac.rs/obrazac_za_sprovodjenje_imunizacije}podaci_o_adresi"/&gt;
 *         &lt;element name="broj_fiksnog_telefona" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="broj_mobilnog_telefona" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="imejl" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="radni_status"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;enumeration value="zaposlen"/&gt;
 *               &lt;enumeration value="nezaposlen"/&gt;
 *               &lt;enumeration value="penzioner"/&gt;
 *               &lt;enumeration value="ucenik"/&gt;
 *               &lt;enumeration value="student"/&gt;
 *               &lt;enumeration value="dete"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="zanimanje_zaposlenog" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;enumeration value="zdravstvena zastita"/&gt;
 *               &lt;enumeration value="socijalna zastita"/&gt;
 *               &lt;enumeration value="prosveta"/&gt;
 *               &lt;enumeration value="MUP"/&gt;
 *               &lt;enumeration value="Vojska RS"/&gt;
 *               &lt;enumeration value="drugo"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="korisnik_ustanove_socijalne_zastite"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;enumeration value="DA"/&gt;
 *               &lt;enumeration value="NE"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="naziv_sedista_ustanove" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "osoba", propOrder = {
    "drzavljanstvo",
    "jmbg",
    "stranoDrzavljanstvo",
    "brojPasosa",
    "prezime",
    "ime",
    "imeRoditelja",
    "pol",
    "datumRodjenja",
    "mestoRodjenja",
    "adresa",
    "brojFiksnogTelefona",
    "brojMobilnogTelefona",
    "imejl",
    "radniStatus",
    "zanimanjeZaposlenog",
    "korisnikUstanoveSocijalneZastite",
    "nazivSedistaUstanove"
})
public class Osoba {

    protected String drzavljanstvo;
    protected Jmbg jmbg;
    @XmlElement(name = "strano_drzavljanstvo")
    protected String stranoDrzavljanstvo;
    @XmlElement(name = "broj_pasosa")
    protected Osoba.BrojPasosa brojPasosa;
    @XmlElement(required = true)
    protected String prezime;
    @XmlElement(required = true)
    protected String ime;
    @XmlElement(name = "ime_roditelja", required = true)
    protected String imeRoditelja;
    @XmlElement(required = true)
    protected String pol;
    @XmlElement(name = "datum_rodjenja", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar datumRodjenja;
    @XmlElement(name = "mesto_rodjenja", required = true)
    protected String mestoRodjenja;
    @XmlElement(required = true)
    protected PodaciOAdresi adresa;
    @XmlElement(name = "broj_fiksnog_telefona", required = true)
    protected String brojFiksnogTelefona;
    @XmlElement(name = "broj_mobilnog_telefona", required = true)
    protected String brojMobilnogTelefona;
    @XmlElement(required = true)
    protected String imejl;
    @XmlElement(name = "radni_status", required = true)
    protected String radniStatus;
    @XmlElement(name = "zanimanje_zaposlenog")
    protected String zanimanjeZaposlenog;
    @XmlElement(name = "korisnik_ustanove_socijalne_zastite", required = true)
    protected String korisnikUstanoveSocijalneZastite;
    @XmlElement(name = "naziv_sedista_ustanove")
    protected String nazivSedistaUstanove;

    /**
     * Gets the value of the drzavljanstvo property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getDrzavljanstvo() {
        return drzavljanstvo;
    }

    /**
     * Sets the value of the drzavljanstvo property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setDrzavljanstvo(String value) {
        this.drzavljanstvo = value;
    }

    /**
     * Gets the value of the jmbg property.
     *
     * @return
     *     possible object is
     *     {@link Jmbg }
     *
     */
    public Jmbg getJmbg() {
        return jmbg;
    }

    /**
     * Sets the value of the jmbg property.
     *
     * @param value
     *     allowed object is
     *     {@link Jmbg }
     *
     */
    public void setJmbg(Jmbg value) {
        this.jmbg = value;
    }

    /**
     * Gets the value of the stranoDrzavljanstvo property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getStranoDrzavljanstvo() {
        return stranoDrzavljanstvo;
    }

    /**
     * Sets the value of the stranoDrzavljanstvo property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setStranoDrzavljanstvo(String value) {
        this.stranoDrzavljanstvo = value;
    }

    /**
     * Gets the value of the brojPasosa property.
     *
     * @return
     *     possible object is
     *     {@link Osoba.BrojPasosa }
     *
     */
    public Osoba.BrojPasosa getBrojPasosa() {
        return brojPasosa;
    }

    /**
     * Sets the value of the brojPasosa property.
     *
     * @param value
     *     allowed object is
     *     {@link Osoba.BrojPasosa }
     *
     */
    public void setBrojPasosa(Osoba.BrojPasosa value) {
        this.brojPasosa = value;
    }

    /**
     * Gets the value of the prezime property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getPrezime() {
        return prezime;
    }

    /**
     * Sets the value of the prezime property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setPrezime(String value) {
        this.prezime = value;
    }

    /**
     * Gets the value of the ime property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getIme() {
        return ime;
    }

    /**
     * Sets the value of the ime property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setIme(String value) {
        this.ime = value;
    }

    /**
     * Gets the value of the imeRoditelja property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getImeRoditelja() {
        return imeRoditelja;
    }

    /**
     * Sets the value of the imeRoditelja property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setImeRoditelja(String value) {
        this.imeRoditelja = value;
    }

    /**
     * Gets the value of the pol property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getPol() {
        return pol;
    }

    /**
     * Sets the value of the pol property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setPol(String value) {
        this.pol = value;
    }

    /**
     * Gets the value of the datumRodjenja property.
     *
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public XMLGregorianCalendar getDatumRodjenja() {
        return datumRodjenja;
    }

    /**
     * Sets the value of the datumRodjenja property.
     *
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public void setDatumRodjenja(XMLGregorianCalendar value) {
        this.datumRodjenja = value;
    }

    /**
     * Gets the value of the mestoRodjenja property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getMestoRodjenja() {
        return mestoRodjenja;
    }

    /**
     * Sets the value of the mestoRodjenja property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setMestoRodjenja(String value) {
        this.mestoRodjenja = value;
    }

    /**
     * Gets the value of the adresa property.
     *
     * @return
     *     possible object is
     *     {@link PodaciOAdresi }
     *
     */
    public PodaciOAdresi getAdresa() {
        return adresa;
    }

    /**
     * Sets the value of the adresa property.
     *
     * @param value
     *     allowed object is
     *     {@link PodaciOAdresi }
     *     
     */
    public void setAdresa(PodaciOAdresi value) {
        this.adresa = value;
    }

    /**
     * Gets the value of the brojFiksnogTelefona property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBrojFiksnogTelefona() {
        return brojFiksnogTelefona;
    }

    /**
     * Sets the value of the brojFiksnogTelefona property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBrojFiksnogTelefona(String value) {
        this.brojFiksnogTelefona = value;
    }

    /**
     * Gets the value of the brojMobilnogTelefona property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBrojMobilnogTelefona() {
        return brojMobilnogTelefona;
    }

    /**
     * Sets the value of the brojMobilnogTelefona property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBrojMobilnogTelefona(String value) {
        this.brojMobilnogTelefona = value;
    }

    /**
     * Gets the value of the imejl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImejl() {
        return imejl;
    }

    /**
     * Sets the value of the imejl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImejl(String value) {
        this.imejl = value;
    }

    /**
     * Gets the value of the radniStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRadniStatus() {
        return radniStatus;
    }

    /**
     * Sets the value of the radniStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRadniStatus(String value) {
        this.radniStatus = value;
    }

    /**
     * Gets the value of the zanimanjeZaposlenog property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getZanimanjeZaposlenog() {
        return zanimanjeZaposlenog;
    }

    /**
     * Sets the value of the zanimanjeZaposlenog property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setZanimanjeZaposlenog(String value) {
        this.zanimanjeZaposlenog = value;
    }

    /**
     * Gets the value of the korisnikUstanoveSocijalneZastite property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKorisnikUstanoveSocijalneZastite() {
        return korisnikUstanoveSocijalneZastite;
    }

    /**
     * Sets the value of the korisnikUstanoveSocijalneZastite property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKorisnikUstanoveSocijalneZastite(String value) {
        this.korisnikUstanoveSocijalneZastite = value;
    }

    /**
     * Gets the value of the nazivSedistaUstanove property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNazivSedistaUstanove() {
        return nazivSedistaUstanove;
    }

    /**
     * Sets the value of the nazivSedistaUstanove property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNazivSedistaUstanove(String value) {
        this.nazivSedistaUstanove = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;simpleContent&gt;
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
     *     &lt;/extension&gt;
     *   &lt;/simpleContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class BrojPasosa {

        @XmlValue
        protected String value;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

    }

}
