//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.01.05 at 12:15:08 AM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.ftn.uns.ac.rs/obrazac_za_sprovodjenje_imunizacije", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package main.java.com.xml.officialbackend.model.obrazac_za_sprovodjenje_imunizacije;
