//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.02.12 at 03:22:10 PM CET 
//


package main.java.com.xml.userbackend.model.lista_cekanja;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.*;
import javax.xml.datatype.XMLGregorianCalendar;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence maxOccurs="unbounded" minOccurs="0"&gt;
 *         &lt;element name="period_cekanja" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
 *         &lt;element name="pacijent" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="tip_vakcine" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="about" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "periodCekanjaAndPacijentAndTipVakcine"
})
@XmlRootElement(name = "lista_cekanja")
public class ListaCekanja {

    @XmlElementRefs({
        @XmlElementRef(name = "period_cekanja", namespace = "http://www.ftn.uns.ac.rs/lista_cekanja", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "pacijent", namespace = "http://www.ftn.uns.ac.rs/lista_cekanja", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "tip_vakcine", namespace = "http://www.ftn.uns.ac.rs/lista_cekanja", type = JAXBElement.class, required = false)
    })
    protected List<JAXBElement<?>> periodCekanjaAndPacijentAndTipVakcine;
    @XmlAttribute(name = "about")
    @XmlSchemaType(name = "anySimpleType")
    protected String about;

    /**
     * Gets the value of the periodCekanjaAndPacijentAndTipVakcine property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the periodCekanjaAndPacijentAndTipVakcine property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPeriodCekanjaAndPacijentAndTipVakcine().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * 
     */
    public List<JAXBElement<?>> getPeriodCekanjaAndPacijentAndTipVakcine() {
        if (periodCekanjaAndPacijentAndTipVakcine == null) {
            periodCekanjaAndPacijentAndTipVakcine = new ArrayList<JAXBElement<?>>();
        }
        return this.periodCekanjaAndPacijentAndTipVakcine;
    }

    /**
     * Gets the value of the about property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAbout() {
        return about;
    }

    /**
     * Sets the value of the about property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAbout(String value) {
        this.about = value;
    }

}
