//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.02.12 at 03:22:10 PM CET 
//


package main.java.com.xml.userbackend.model.lista_cekanja;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the rs.ac.uns.ftn.lista_cekanja package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ListaCekanjaPeriodCekanja_QNAME = new QName("http://www.ftn.uns.ac.rs/lista_cekanja", "period_cekanja");
    private final static QName _ListaCekanjaPacijent_QNAME = new QName("http://www.ftn.uns.ac.rs/lista_cekanja", "pacijent");
    private final static QName _ListaCekanjaTipVakcine_QNAME = new QName("http://www.ftn.uns.ac.rs/lista_cekanja", "tip_vakcine");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: rs.ac.uns.ftn.lista_cekanja
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ListaCekanja }
     * 
     */
    public ListaCekanja createListaCekanja() {
        return new ListaCekanja();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/lista_cekanja", name = "period_cekanja", scope = ListaCekanja.class)
    public JAXBElement<XMLGregorianCalendar> createListaCekanjaPeriodCekanja(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_ListaCekanjaPeriodCekanja_QNAME, XMLGregorianCalendar.class, ListaCekanja.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/lista_cekanja", name = "pacijent", scope = ListaCekanja.class)
    public JAXBElement<String> createListaCekanjaPacijent(String value) {
        return new JAXBElement<String>(_ListaCekanjaPacijent_QNAME, String.class, ListaCekanja.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/lista_cekanja", name = "tip_vakcine", scope = ListaCekanja.class)
    public JAXBElement<String> createListaCekanjaTipVakcine(String value) {
        return new JAXBElement<String>(_ListaCekanjaTipVakcine_QNAME, String.class, ListaCekanja.class, value);
    }

}
