//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.01.05 at 12:22:27 AM CET 
//


package main.java.com.xml.officialbackend.model.digitalni_sertifikat;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="qr_kod" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="podaci_o_sertifikatu" type="{http://www.ftn.uns.ac.rs/digitalni_sertifikat}podaci_o_sertifikatu"/&gt;
 *         &lt;element name="licni_podaci" type="{http://www.ftn.uns.ac.rs/digitalni_sertifikat}licni_podaci"/&gt;
 *         &lt;element name="podaci_o_vakcinaciji" type="{http://www.ftn.uns.ac.rs/digitalni_sertifikat}podaci_o_vakcinaciji"/&gt;
 *         &lt;element name="testovi"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="test" type="{http://www.ftn.uns.ac.rs/digitalni_sertifikat}test" maxOccurs="unbounded"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "qrKod",
    "podaciOSertifikatu",
    "licniPodaci",
    "podaciOVakcinaciji",
    "testovi"
})
@XmlRootElement(name = "digitalni_zeleni_sertifikat")
public class DigitalniZeleniSertifikat {

    @XmlElement(name = "qr_kod", required = true)
    protected String qrKod;
    @XmlElement(name = "podaci_o_sertifikatu", required = true)
    protected PodaciOSertifikatu podaciOSertifikatu;
    @XmlElement(name = "licni_podaci", required = true)
    protected LicniPodaci licniPodaci;
    @XmlElement(name = "podaci_o_vakcinaciji", required = true)
    protected PodaciOVakcinaciji podaciOVakcinaciji;
    @XmlElement(required = true)
    protected DigitalniZeleniSertifikat.Testovi testovi;

    /**
     * Gets the value of the qrKod property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQrKod() {
        return qrKod;
    }

    /**
     * Sets the value of the qrKod property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQrKod(String value) {
        this.qrKod = value;
    }

    /**
     * Gets the value of the podaciOSertifikatu property.
     * 
     * @return
     *     possible object is
     *     {@link PodaciOSertifikatu }
     *     
     */
    public PodaciOSertifikatu getPodaciOSertifikatu() {
        return podaciOSertifikatu;
    }

    /**
     * Sets the value of the podaciOSertifikatu property.
     * 
     * @param value
     *     allowed object is
     *     {@link PodaciOSertifikatu }
     *     
     */
    public void setPodaciOSertifikatu(PodaciOSertifikatu value) {
        this.podaciOSertifikatu = value;
    }

    /**
     * Gets the value of the licniPodaci property.
     * 
     * @return
     *     possible object is
     *     {@link LicniPodaci }
     *     
     */
    public LicniPodaci getLicniPodaci() {
        return licniPodaci;
    }

    /**
     * Sets the value of the licniPodaci property.
     * 
     * @param value
     *     allowed object is
     *     {@link LicniPodaci }
     *     
     */
    public void setLicniPodaci(LicniPodaci value) {
        this.licniPodaci = value;
    }

    /**
     * Gets the value of the podaciOVakcinaciji property.
     * 
     * @return
     *     possible object is
     *     {@link PodaciOVakcinaciji }
     *     
     */
    public PodaciOVakcinaciji getPodaciOVakcinaciji() {
        return podaciOVakcinaciji;
    }

    /**
     * Sets the value of the podaciOVakcinaciji property.
     * 
     * @param value
     *     allowed object is
     *     {@link PodaciOVakcinaciji }
     *     
     */
    public void setPodaciOVakcinaciji(PodaciOVakcinaciji value) {
        this.podaciOVakcinaciji = value;
    }

    /**
     * Gets the value of the testovi property.
     * 
     * @return
     *     possible object is
     *     {@link DigitalniZeleniSertifikat.Testovi }
     *     
     */
    public DigitalniZeleniSertifikat.Testovi getTestovi() {
        return testovi;
    }

    /**
     * Sets the value of the testovi property.
     * 
     * @param value
     *     allowed object is
     *     {@link DigitalniZeleniSertifikat.Testovi }
     *     
     */
    public void setTestovi(DigitalniZeleniSertifikat.Testovi value) {
        this.testovi = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="test" type="{http://www.ftn.uns.ac.rs/digitalni_sertifikat}test" maxOccurs="unbounded"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "test"
    })
    public static class Testovi {

        @XmlElement(required = true)
        protected List<Test> test;

        /**
         * Gets the value of the test property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the test property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getTest().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Test }
         * 
         * 
         */
        public List<Test> getTest() {
            if (test == null) {
                test = new ArrayList<Test>();
            }
            return this.test;
        }

    }

}
