//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.02.10 at 06:03:11 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.ftn.uns.ac.rs/digitalni_sertifikat", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package main.java.com.xml.officialbackend.model.digitalni_sertifikat;
