//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.01.05 at 12:22:27 AM CET 
//


package main.java.com.xml.officialbackend.model.digitalni_sertifikat;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for podaci_o_sertifikatu complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="podaci_o_sertifikatu"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="broj_sertifikata"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;pattern value="\d{6}/\d{2}"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="datum_vreme_izdavanja" type="{http://www.w3.org/2001/XMLSchema}dateTime"/&gt;
 *         &lt;element name="sertifikat_izdaje" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="digitalni_potpis" type="{http://www.ftn.uns.ac.rs/digitalni_sertifikat}digitalni_potpis"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "podaci_o_sertifikatu", propOrder = {
    "brojSertifikata",
    "datumVremeIzdavanja",
    "sertifikatIzdaje",
    "digitalniPotpis"
})
public class PodaciOSertifikatu {

    @XmlElement(name = "broj_sertifikata", required = true)
    protected String brojSertifikata;
    @XmlElement(name = "datum_vreme_izdavanja", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar datumVremeIzdavanja;
    @XmlElement(name = "sertifikat_izdaje", required = true)
    protected String sertifikatIzdaje;
    @XmlElement(name = "digitalni_potpis", required = true)
    protected DigitalniPotpis digitalniPotpis;

    /**
     * Gets the value of the brojSertifikata property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBrojSertifikata() {
        return brojSertifikata;
    }

    /**
     * Sets the value of the brojSertifikata property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBrojSertifikata(String value) {
        this.brojSertifikata = value;
    }

    /**
     * Gets the value of the datumVremeIzdavanja property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDatumVremeIzdavanja() {
        return datumVremeIzdavanja;
    }

    /**
     * Sets the value of the datumVremeIzdavanja property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDatumVremeIzdavanja(XMLGregorianCalendar value) {
        this.datumVremeIzdavanja = value;
    }

    /**
     * Gets the value of the sertifikatIzdaje property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSertifikatIzdaje() {
        return sertifikatIzdaje;
    }

    /**
     * Sets the value of the sertifikatIzdaje property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSertifikatIzdaje(String value) {
        this.sertifikatIzdaje = value;
    }

    /**
     * Gets the value of the digitalniPotpis property.
     * 
     * @return
     *     possible object is
     *     {@link DigitalniPotpis }
     *     
     */
    public DigitalniPotpis getDigitalniPotpis() {
        return digitalniPotpis;
    }

    /**
     * Sets the value of the digitalniPotpis property.
     * 
     * @param value
     *     allowed object is
     *     {@link DigitalniPotpis }
     *     
     */
    public void setDigitalniPotpis(DigitalniPotpis value) {
        this.digitalniPotpis = value;
    }

}
