//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.02.17 at 03:32:25 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.ftn.uns.ac.rs/zahtev_za_sertifikat", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package main.java.com.xml.userbackend.model.zahtev_za_sertifikat;
