//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.01.10 at 08:16:01 PM CET 
//


package main.java.com.xml.officialbackend.model.potvrda_o_vakcinaciji;

import javax.xml.bind.annotation.*;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="sifra_potvrde_vakcinacije"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;pattern value="\d{7}-\d{7}"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="licni_podaci" type="{http://www.ftn.uns.ac.rs/potvrda_o_vakcinaciji}osoba"/&gt;
 *         &lt;element name="podaci_o_vakcinaciji" type="{http://www.ftn.uns.ac.rs/potvrda_o_vakcinaciji}vakcinacija"/&gt;
 *         &lt;element name="datum_izdavanja_potvrde"&gt;
 *           &lt;complexType&gt;
 *             &lt;simpleContent&gt;
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;date"&gt;
 *                 &lt;attribute name="property" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
 *               &lt;/extension&gt;
 *             &lt;/simpleContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="qr-kod"&gt;
 *           &lt;complexType&gt;
 *             &lt;simpleContent&gt;
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
 *                 &lt;attribute name="property" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
 *               &lt;/extension&gt;
 *             &lt;/simpleContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="about" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
 *       &lt;attribute name="typeof" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "sifraPotvrdeVakcinacije",
    "licniPodaci",
    "podaciOVakcinaciji",
    "datumIzdavanjaPotvrde",
    "qrKod"
})
@XmlRootElement(name = "potvrda_o_vakcinaciji")
public class PotvrdaOVakcinaciji {

    @XmlElement(name = "sifra_potvrde_vakcinacije", required = true)
    protected String sifraPotvrdeVakcinacije;
    @XmlElement(name = "licni_podaci", required = true)
    protected Osoba licniPodaci;
    @XmlElement(name = "podaci_o_vakcinaciji", required = true)
    protected Vakcinacija podaciOVakcinaciji;
    @XmlElement(name = "datum_izdavanja_potvrde", required = true)
    protected PotvrdaOVakcinaciji.DatumIzdavanjaPotvrde datumIzdavanjaPotvrde;
    @XmlElement(name = "qr-kod", required = true)
    protected PotvrdaOVakcinaciji.QrKod qrKod;
    @XmlAttribute(name = "about")
    @XmlSchemaType(name = "anySimpleType")
    protected String about;
    @XmlAttribute(name = "typeof")
    @XmlSchemaType(name = "anySimpleType")
    protected String typeof;

    /**
     * Gets the value of the sifraPotvrdeVakcinacije property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getSifraPotvrdeVakcinacije() {
        return sifraPotvrdeVakcinacije;
    }

    /**
     * Sets the value of the sifraPotvrdeVakcinacije property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setSifraPotvrdeVakcinacije(String value) {
        this.sifraPotvrdeVakcinacije = value;
    }

    /**
     * Gets the value of the licniPodaci property.
     *
     * @return
     *     possible object is
     *     {@link Osoba }
     *
     */
    public Osoba getLicniPodaci() {
        return licniPodaci;
    }

    /**
     * Sets the value of the licniPodaci property.
     *
     * @param value
     *     allowed object is
     *     {@link Osoba }
     *
     */
    public void setLicniPodaci(Osoba value) {
        this.licniPodaci = value;
    }

    /**
     * Gets the value of the podaciOVakcinaciji property.
     *
     * @return
     *     possible object is
     *     {@link Vakcinacija }
     *
     */
    public Vakcinacija getPodaciOVakcinaciji() {
        return podaciOVakcinaciji;
    }

    /**
     * Sets the value of the podaciOVakcinaciji property.
     *
     * @param value
     *     allowed object is
     *     {@link Vakcinacija }
     *
     */
    public void setPodaciOVakcinaciji(Vakcinacija value) {
        this.podaciOVakcinaciji = value;
    }

    /**
     * Gets the value of the datumIzdavanjaPotvrde property.
     *
     * @return
     *     possible object is
     *     {@link PotvrdaOVakcinaciji.DatumIzdavanjaPotvrde }
     *
     */
    public PotvrdaOVakcinaciji.DatumIzdavanjaPotvrde getDatumIzdavanjaPotvrde() {
        return datumIzdavanjaPotvrde;
    }

    /**
     * Sets the value of the datumIzdavanjaPotvrde property.
     *
     * @param value
     *     allowed object is
     *     {@link PotvrdaOVakcinaciji.DatumIzdavanjaPotvrde }
     *
     */
    public void setDatumIzdavanjaPotvrde(PotvrdaOVakcinaciji.DatumIzdavanjaPotvrde value) {
        this.datumIzdavanjaPotvrde = value;
    }

    /**
     * Gets the value of the qrKod property.
     *
     * @return
     *     possible object is
     *     {@link PotvrdaOVakcinaciji.QrKod }
     *
     */
    public PotvrdaOVakcinaciji.QrKod getQrKod() {
        return qrKod;
    }

    /**
     * Sets the value of the qrKod property.
     *
     * @param value
     *     allowed object is
     *     {@link PotvrdaOVakcinaciji.QrKod }
     *
     */
    public void setQrKod(PotvrdaOVakcinaciji.QrKod value) {
        this.qrKod = value;
    }

    /**
     * Gets the value of the about property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAbout() {
        return about;
    }

    /**
     * Sets the value of the about property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAbout(String value) {
        this.about = value;
    }

    /**
     * Gets the value of the typeof property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTypeof() {
        return typeof;
    }

    /**
     * Sets the value of the typeof property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTypeof(String value) {
        this.typeof = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;simpleContent&gt;
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;date"&gt;
     *       &lt;attribute name="property" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
     *     &lt;/extension&gt;
     *   &lt;/simpleContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class DatumIzdavanjaPotvrde {

        @XmlValue
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar value;
        @XmlAttribute(name = "property")
        @XmlSchemaType(name = "anySimpleType")
        protected String property;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setValue(XMLGregorianCalendar value) {
            this.value = value;
        }

        /**
         * Gets the value of the property property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getProperty() {
            return property;
        }

        /**
         * Sets the value of the property property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setProperty(String value) {
            this.property = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;simpleContent&gt;
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
     *       &lt;attribute name="property" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
     *     &lt;/extension&gt;
     *   &lt;/simpleContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class QrKod {

        @XmlValue
        protected String value;
        @XmlAttribute(name = "property")
        @XmlSchemaType(name = "anySimpleType")
        protected String property;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the property property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getProperty() {
            return property;
        }

        /**
         * Sets the value of the property property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setProperty(String value) {
            this.property = value;
        }

    }

}
