//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.02.14 at 07:08:11 PM CET 
//


package main.java.com.xml.officialbackend.model.lista_cekanja;

import javax.xml.bind.annotation.*;
import javax.xml.datatype.XMLGregorianCalendar;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence maxOccurs="unbounded" minOccurs="0"&gt;
 *         &lt;element name="stavka"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="period_cekanja" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
 *                   &lt;element name="pacijent" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="tip_vakcine" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "stavka"
})
@XmlRootElement(name = "lista_cekanja")
public class ListaCekanja {

    protected List<ListaCekanja.Stavka> stavka;

    /**
     * Gets the value of the stavka property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the stavka property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getStavka().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ListaCekanja.Stavka }
     *
     *
     */
    public List<ListaCekanja.Stavka> getStavka() {
        if (stavka == null) {
            stavka = new ArrayList<ListaCekanja.Stavka>();
        }
        return this.stavka;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="period_cekanja" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
     *         &lt;element name="pacijent" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="tip_vakcine" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "periodCekanja",
        "pacijent",
        "tipVakcine"
    })
    public static class Stavka {

        @XmlElement(name = "period_cekanja", required = true)
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar periodCekanja;
        @XmlElement(required = true)
        protected String pacijent;
        @XmlElement(name = "tip_vakcine", required = true)
        protected String tipVakcine;

        /**
         * Gets the value of the periodCekanja property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getPeriodCekanja() {
            return periodCekanja;
        }

        /**
         * Sets the value of the periodCekanja property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setPeriodCekanja(XMLGregorianCalendar value) {
            this.periodCekanja = value;
        }

        /**
         * Gets the value of the pacijent property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPacijent() {
            return pacijent;
        }

        /**
         * Sets the value of the pacijent property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPacijent(String value) {
            this.pacijent = value;
        }

        /**
         * Gets the value of the tipVakcine property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTipVakcine() {
            return tipVakcine;
        }

        /**
         * Sets the value of the tipVakcine property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTipVakcine(String value) {
            this.tipVakcine = value;
        }

    }

}
