//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.01.10 at 09:32:51 PM CET 
//


package main.java.com.xml.officialbackend.model.interesovanje;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for vakcinacija complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="vakcinacija"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="opstina_vakcinisanja" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="tip_vakcine" type="{http://www.ftn.uns.ac.rs/interesovanje}tip_vakcine"/&gt;
 *         &lt;element name="dobrovoljni_davalac_krvi"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;enumeration value="Da"/&gt;
 *               &lt;enumeration value="Ne"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "vakcinacija", propOrder = {
    "opstinaVakcinisanja",
    "tipVakcine",
    "dobrovoljniDavalacKrvi"
})
public class Vakcinacija {

    @XmlElement(name = "opstina_vakcinisanja", required = true)
    protected String opstinaVakcinisanja;
    @XmlElement(name = "tip_vakcine", required = true)
    protected TipVakcine tipVakcine;
    @XmlElement(name = "dobrovoljni_davalac_krvi", required = true)
    protected String dobrovoljniDavalacKrvi;

    /**
     * Gets the value of the opstinaVakcinisanja property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getOpstinaVakcinisanja() {
        return opstinaVakcinisanja;
    }

    /**
     * Sets the value of the opstinaVakcinisanja property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setOpstinaVakcinisanja(String value) {
        this.opstinaVakcinisanja = value;
    }

    /**
     * Gets the value of the tipVakcine property.
     *
     * @return
     *     possible object is
     *     {@link TipVakcine }
     *
     */
    public TipVakcine getTipVakcine() {
        return tipVakcine;
    }

    /**
     * Sets the value of the tipVakcine property.
     *
     * @param value
     *     allowed object is
     *     {@link TipVakcine }
     *     
     */
    public void setTipVakcine(TipVakcine value) {
        this.tipVakcine = value;
    }

    /**
     * Gets the value of the dobrovoljniDavalacKrvi property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDobrovoljniDavalacKrvi() {
        return dobrovoljniDavalacKrvi;
    }

    /**
     * Sets the value of the dobrovoljniDavalacKrvi property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDobrovoljniDavalacKrvi(String value) {
        this.dobrovoljniDavalacKrvi = value;
    }

    @Override
    public String toString() {
        return "Vakcinacija{" +
                "opstinaVakcinisanja='" + opstinaVakcinisanja + '\'' +
                ", tipVakcine=" + tipVakcine +
                ", dobrovoljniDavalacKrvi='" + dobrovoljniDavalacKrvi + '\'' +
                '}';
    }
}
