//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.02.16 at 05:55:23 PM CET 
//


package main.java.com.xml.userbackend.model.potvrda_o_vakcinaciji;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the rs.ac.uns.ftn.potvrda_o_vakcinaciji package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: rs.ac.uns.ftn.potvrda_o_vakcinaciji
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link main.java.com.xml.userbackend.model.potvrda_o_vakcinaciji.PotvrdaOVakcinaciji }
     * 
     */
    public main.java.com.xml.userbackend.model.potvrda_o_vakcinaciji.PotvrdaOVakcinaciji createPotvrdaOVakcinaciji() {
        return new main.java.com.xml.userbackend.model.potvrda_o_vakcinaciji.PotvrdaOVakcinaciji();
    }

    /**
     * Create an instance of {@link main.java.com.xml.userbackend.model.potvrda_o_vakcinaciji.Vakcinacija }
     * 
     */
    public main.java.com.xml.userbackend.model.potvrda_o_vakcinaciji.Vakcinacija createVakcinacija() {
        return new main.java.com.xml.userbackend.model.potvrda_o_vakcinaciji.Vakcinacija();
    }

    /**
     * Create an instance of {@link Osoba }
     * 
     */
    public Osoba createOsoba() {
        return new Osoba();
    }

    /**
     * Create an instance of {@link main.java.com.xml.userbackend.model.potvrda_o_vakcinaciji.PotvrdaOVakcinaciji.DatumIzdavanjaPotvrde }
     * 
     */
    public main.java.com.xml.userbackend.model.potvrda_o_vakcinaciji.PotvrdaOVakcinaciji.DatumIzdavanjaPotvrde createPotvrdaOVakcinacijiDatumIzdavanjaPotvrde() {
        return new main.java.com.xml.userbackend.model.potvrda_o_vakcinaciji.PotvrdaOVakcinaciji.DatumIzdavanjaPotvrde();
    }

    /**
     * Create an instance of {@link main.java.com.xml.userbackend.model.potvrda_o_vakcinaciji.PotvrdaOVakcinaciji.QrKod }
     * 
     */
    public main.java.com.xml.userbackend.model.potvrda_o_vakcinaciji.PotvrdaOVakcinaciji.QrKod createPotvrdaOVakcinacijiQrKod() {
        return new main.java.com.xml.userbackend.model.potvrda_o_vakcinaciji.PotvrdaOVakcinaciji.QrKod();
    }

    /**
     * Create an instance of {@link main.java.com.xml.userbackend.model.potvrda_o_vakcinaciji.Doza }
     * 
     */
    public main.java.com.xml.userbackend.model.potvrda_o_vakcinaciji.Doza createDoza() {
        return new main.java.com.xml.userbackend.model.potvrda_o_vakcinaciji.Doza();
    }

    /**
     * Create an instance of {@link main.java.com.xml.userbackend.model.potvrda_o_vakcinaciji.Jmbg }
     * 
     */
    public main.java.com.xml.userbackend.model.potvrda_o_vakcinaciji.Jmbg createJmbg() {
        return new main.java.com.xml.userbackend.model.potvrda_o_vakcinaciji.Jmbg();
    }

    /**
     * Create an instance of {@link main.java.com.xml.userbackend.model.potvrda_o_vakcinaciji.Vakcinacija.Doze }
     * 
     */
    public main.java.com.xml.userbackend.model.potvrda_o_vakcinaciji.Vakcinacija.Doze createVakcinacijaDoze() {
        return new main.java.com.xml.userbackend.model.potvrda_o_vakcinaciji.Vakcinacija.Doze();
    }

    public PotvrdaOVakcinacijiList createList() {
        return new PotvrdaOVakcinacijiList();
    }

}
