//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.01.04 at 11:47:53 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.ftn.uns.ac.rs/potvrda_o_vakcinaciji", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package main.java.com.xml.userbackend.model.potvrda_o_vakcinaciji;
