//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.01.04 at 11:47:53 PM CET 
//


package main.java.com.xml.userbackend.model.interesovanje;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="licni_podaci" type="{http://www.ftn.uns.ac.rs/interesovanje}osoba"/&gt;
 *         &lt;element name="podaci_o_vakcinisanju" type="{http://www.ftn.uns.ac.rs/interesovanje}vakcinacija"/&gt;
 *         &lt;element name="datum_podnosenja" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "licniPodaci",
    "podaciOVakcinisanju",
    "datumPodnosenja"
})
@XmlRootElement(name = "interesovanje_za_vakcinisanje")
public class InteresovanjeZaVakcinisanje {

    @XmlElement(name = "licni_podaci", required = true)
    protected Osoba licniPodaci;
    @XmlElement(name = "podaci_o_vakcinisanju", required = true)
    protected Vakcinacija podaciOVakcinisanju;
    @XmlElement(name = "datum_podnosenja", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar datumPodnosenja;

    /**
     * Gets the value of the licniPodaci property.
     * 
     * @return
     *     possible object is
     *     {@link Osoba }
     *     
     */
    public Osoba getLicniPodaci() {
        return licniPodaci;
    }

    /**
     * Sets the value of the licniPodaci property.
     * 
     * @param value
     *     allowed object is
     *     {@link Osoba }
     *     
     */
    public void setLicniPodaci(Osoba value) {
        this.licniPodaci = value;
    }

    /**
     * Gets the value of the podaciOVakcinisanju property.
     * 
     * @return
     *     possible object is
     *     {@link Vakcinacija }
     *     
     */
    public Vakcinacija getPodaciOVakcinisanju() {
        return podaciOVakcinisanju;
    }

    /**
     * Sets the value of the podaciOVakcinisanju property.
     * 
     * @param value
     *     allowed object is
     *     {@link Vakcinacija }
     *     
     */
    public void setPodaciOVakcinisanju(Vakcinacija value) {
        this.podaciOVakcinisanju = value;
    }

    /**
     * Gets the value of the datumPodnosenja property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDatumPodnosenja() {
        return datumPodnosenja;
    }

    /**
     * Sets the value of the datumPodnosenja property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDatumPodnosenja(XMLGregorianCalendar value) {
        this.datumPodnosenja = value;
    }

}
