//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.02.10 at 06:03:11 PM CET 
//


package main.java.com.xml.userbackend.model.digitalni_sertifikat;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the rs.ac.uns.ftn.digitalni_sertifikat package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: rs.ac.uns.ftn.digitalni_sertifikat
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link DigitalniZeleniSertifikat }
     * 
     */
    public DigitalniZeleniSertifikat createDigitalniZeleniSertifikat() {
        return new DigitalniZeleniSertifikat();
    }

    /**
     * Create an instance of {@link PodaciOVakcinaciji }
     * 
     */
    public PodaciOVakcinaciji createPodaciOVakcinaciji() {
        return new PodaciOVakcinaciji();
    }

    /**
     * Create an instance of {@link PodaciOSertifikatu }
     * 
     */
    public PodaciOSertifikatu createPodaciOSertifikatu() {
        return new PodaciOSertifikatu();
    }

    /**
     * Create an instance of {@link DigitalniZeleniSertifikat.QrKod }
     * 
     */
    public DigitalniZeleniSertifikat.QrKod createDigitalniZeleniSertifikatQrKod() {
        return new DigitalniZeleniSertifikat.QrKod();
    }

    /**
     * Create an instance of {@link LicniPodaci }
     *
     */
    public LicniPodaci createLicniPodaci() {
        return new LicniPodaci();
    }

    /**
     * Create an instance of {@link DigitalniZeleniSertifikat.Testovi }
     *
     */
    public DigitalniZeleniSertifikat.Testovi createDigitalniZeleniSertifikatTestovi() {
        return new DigitalniZeleniSertifikat.Testovi();
    }

    /**
     * Create an instance of {@link Doza }
     *
     */
    public Doza createDoza() {
        return new Doza();
    }

    /**
     * Create an instance of {@link Test }
     * 
     */
    public Test createTest() {
        return new Test();
    }

    /**
     * Create an instance of {@link Jmbg }
     * 
     */
    public Jmbg createJmbg() {
        return new Jmbg();
    }

    /**
     * Create an instance of {@link BrojPasosa }
     * 
     */
    public BrojPasosa createBrojPasosa() {
        return new BrojPasosa();
    }

    /**
     * Create an instance of {@link PodaciOVakcinaciji.Doze }
     * 
     */
    public PodaciOVakcinaciji.Doze createPodaciOVakcinacijiDoze() {
        return new PodaciOVakcinaciji.Doze();
    }

    /**
     * Create an instance of {@link PodaciOSertifikatu.DatumVremeIzdavanja }
     * 
     */
    public PodaciOSertifikatu.DatumVremeIzdavanja createPodaciOSertifikatuDatumVremeIzdavanja() {
        return new PodaciOSertifikatu.DatumVremeIzdavanja();
    }

}
